services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: erp_user
      RABBITMQ_DEFAULT_PASS: erp_pass
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: